{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dc.dhavalchandegara",
    "module": "toastutils",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "toastutils-1.0.0.aar",
          "url": "toastutils-1.0.0.aar",
          "size": 2596,
          "sha512": "06c719071556c541318ac383740de5ddb2c7d18029a7f59b6b6b0b5d24e0dbdf057db795b3bfb2560c184e02e71d7a418af8dd344b2ee6b39ccbae2ee4c6cb2b",
          "sha256": "3525af98910bf21fb4cd45d5352d5fb75acfccc932a3fc615cf4c7d09a597057",
          "sha1": "a78ae03d0f53b9cea7cb8861731e9e7c4875d8a0",
          "md5": "3d24eb33bad8da09a5e180f7ccb401f0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "toastutils-1.0.0.aar",
          "url": "toastutils-1.0.0.aar",
          "size": 2596,
          "sha512": "06c719071556c541318ac383740de5ddb2c7d18029a7f59b6b6b0b5d24e0dbdf057db795b3bfb2560c184e02e71d7a418af8dd344b2ee6b39ccbae2ee4c6cb2b",
          "sha256": "3525af98910bf21fb4cd45d5352d5fb75acfccc932a3fc615cf4c7d09a597057",
          "sha1": "a78ae03d0f53b9cea7cb8861731e9e7c4875d8a0",
          "md5": "3d24eb33bad8da09a5e180f7ccb401f0"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "toastutils-1.0.0-sources.jar",
          "url": "toastutils-1.0.0-sources.jar",
          "size": 1381,
          "sha512": "a4aec2cdc109abb567ab321c89c7eb4e4221fb123955d012ae60d522a2365bca2077dfab2f2e1c9f04d842a2ba6e6dc2830ad2a09ba19df4168902a96c6fa90b",
          "sha256": "8ba4177b7c72cdc660204fc0aae6c8fca41a3f185338e0cceabd9bebaf20bd96",
          "sha1": "22efe5232e4af196fdd27d68f56b56d925db3fb3",
          "md5": "d295f1d2d73a04c64f9843fd9f055ab5"
        }
      ]
    }
  ]
}
